/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as HostsIdRouteImport } from './routes/hosts.$id'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as CheckinEventIdRouteImport } from './routes/checkin.$eventId'
import { Route as ApiExportAttendeesRouteImport } from './routes/api/export-attendees'
import { Route as EventsIdIndexRouteImport } from './routes/events.$id.index'
import { Route as EventsIdGalleryRouteImport } from './routes/events.$id.gallery'
import { Route as EventsIdEditRouteImport } from './routes/events.$id.edit'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsIdRoute = HostsIdRouteImport.update({
  id: '/hosts/$id',
  path: '/hosts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinEventIdRoute = CheckinEventIdRouteImport.update({
  id: '/checkin/$eventId',
  path: '/checkin/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportAttendeesRoute = ApiExportAttendeesRouteImport.update({
  id: '/api/export-attendees',
  path: '/api/export-attendees',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdIndexRoute = EventsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsIdRoute,
} as any)
const EventsIdGalleryRoute = EventsIdGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => EventsIdRoute,
} as any)
const EventsIdEditRoute = EventsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => EventsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/tickets': typeof TicketsRoute
  '/api/export-attendees': typeof ApiExportAttendeesRoute
  '/checkin/$eventId': typeof CheckinEventIdRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/events/new': typeof EventsNewRoute
  '/hosts/$id': typeof HostsIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/events/$id/edit': typeof EventsIdEditRoute
  '/events/$id/gallery': typeof EventsIdGalleryRoute
  '/events/$id/': typeof EventsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/tickets': typeof TicketsRoute
  '/api/export-attendees': typeof ApiExportAttendeesRoute
  '/checkin/$eventId': typeof CheckinEventIdRoute
  '/events/new': typeof EventsNewRoute
  '/hosts/$id': typeof HostsIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/events/$id/edit': typeof EventsIdEditRoute
  '/events/$id/gallery': typeof EventsIdGalleryRoute
  '/events/$id': typeof EventsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/tickets': typeof TicketsRoute
  '/api/export-attendees': typeof ApiExportAttendeesRoute
  '/checkin/$eventId': typeof CheckinEventIdRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/events/new': typeof EventsNewRoute
  '/hosts/$id': typeof HostsIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/events/$id/edit': typeof EventsIdEditRoute
  '/events/$id/gallery': typeof EventsIdGalleryRoute
  '/events/$id/': typeof EventsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/my-events'
    | '/profile'
    | '/reports'
    | '/signup'
    | '/team'
    | '/tickets'
    | '/api/export-attendees'
    | '/checkin/$eventId'
    | '/events/$id'
    | '/events/new'
    | '/hosts/$id'
    | '/invite/$token'
    | '/events/$id/edit'
    | '/events/$id/gallery'
    | '/events/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/my-events'
    | '/profile'
    | '/reports'
    | '/signup'
    | '/team'
    | '/tickets'
    | '/api/export-attendees'
    | '/checkin/$eventId'
    | '/events/new'
    | '/hosts/$id'
    | '/invite/$token'
    | '/events/$id/edit'
    | '/events/$id/gallery'
    | '/events/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/my-events'
    | '/profile'
    | '/reports'
    | '/signup'
    | '/team'
    | '/tickets'
    | '/api/export-attendees'
    | '/checkin/$eventId'
    | '/events/$id'
    | '/events/new'
    | '/hosts/$id'
    | '/invite/$token'
    | '/events/$id/edit'
    | '/events/$id/gallery'
    | '/events/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  MyEventsRoute: typeof MyEventsRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  SignupRoute: typeof SignupRoute
  TeamRoute: typeof TeamRoute
  TicketsRoute: typeof TicketsRoute
  ApiExportAttendeesRoute: typeof ApiExportAttendeesRoute
  CheckinEventIdRoute: typeof CheckinEventIdRoute
  EventsIdRoute: typeof EventsIdRouteWithChildren
  EventsNewRoute: typeof EventsNewRoute
  HostsIdRoute: typeof HostsIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$id': {
      id: '/hosts/$id'
      path: '/hosts/$id'
      fullPath: '/hosts/$id'
      preLoaderRoute: typeof HostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/$eventId': {
      id: '/checkin/$eventId'
      path: '/checkin/$eventId'
      fullPath: '/checkin/$eventId'
      preLoaderRoute: typeof CheckinEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export-attendees': {
      id: '/api/export-attendees'
      path: '/api/export-attendees'
      fullPath: '/api/export-attendees'
      preLoaderRoute: typeof ApiExportAttendeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id/': {
      id: '/events/$id/'
      path: '/'
      fullPath: '/events/$id/'
      preLoaderRoute: typeof EventsIdIndexRouteImport
      parentRoute: typeof EventsIdRoute
    }
    '/events/$id/gallery': {
      id: '/events/$id/gallery'
      path: '/gallery'
      fullPath: '/events/$id/gallery'
      preLoaderRoute: typeof EventsIdGalleryRouteImport
      parentRoute: typeof EventsIdRoute
    }
    '/events/$id/edit': {
      id: '/events/$id/edit'
      path: '/edit'
      fullPath: '/events/$id/edit'
      preLoaderRoute: typeof EventsIdEditRouteImport
      parentRoute: typeof EventsIdRoute
    }
  }
}

interface EventsIdRouteChildren {
  EventsIdEditRoute: typeof EventsIdEditRoute
  EventsIdGalleryRoute: typeof EventsIdGalleryRoute
  EventsIdIndexRoute: typeof EventsIdIndexRoute
}

const EventsIdRouteChildren: EventsIdRouteChildren = {
  EventsIdEditRoute: EventsIdEditRoute,
  EventsIdGalleryRoute: EventsIdGalleryRoute,
  EventsIdIndexRoute: EventsIdIndexRoute,
}

const EventsIdRouteWithChildren = EventsIdRoute._addFileChildren(
  EventsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  MyEventsRoute: MyEventsRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  SignupRoute: SignupRoute,
  TeamRoute: TeamRoute,
  TicketsRoute: TicketsRoute,
  ApiExportAttendeesRoute: ApiExportAttendeesRoute,
  CheckinEventIdRoute: CheckinEventIdRoute,
  EventsIdRoute: EventsIdRouteWithChildren,
  EventsNewRoute: EventsNewRoute,
  HostsIdRoute: HostsIdRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
